"""
xpress_reinsert.py -- Xpress-assisted exact reinsertion for baseline_greedy's
Phase-3 improvement loop (_improve).

Scope, deliberately narrow: given a small batch of removed blocks (K <= ~5,
see baseline_greedy._improve's k_values) and the fixed context of every
other currently-placed block, choose one (bay, orientation, x, y, entry,
exit) candidate per removed block from a pre-scored candidate list, subject
to no two removed blocks' candidates spatially/temporally conflicting with
each other -- minimizing total candidate cost (_placement_score, the same
scoring function used everywhere else in this codebase).

This is NOT a general geometric packing MIP. Candidates are generated by
the exact same _candidate_positions / _find_earliest_slot search
baseline_greedy already runs for plain greedy placement, so this module
adds no new geometry-modeling risk -- each candidate is already
individually feasible against the fixed (non-removed) context on its own.
The only thing Xpress adds is choosing the JOINTLY best combination among
the K removed blocks instead of placing them one at a time greedily, which
is a small, well-scoped independent-set-style assignment problem: binary
y[block, candidate], "exactly one candidate per block", and a "not both" cut
for every pair of candidates (from two different removed blocks) that
would collide in space and time.

Whatever this proposes is re-validated by utils.check_feasibility in
_improve's caller before being accepted or rolled back, exactly like every
other candidate solution in this codebase -- so an imperfect conflict model
here can only ever cause a proposal to be (correctly) rejected, never
accepted incorrectly. reinsert() returns None on any failure (Xpress not
importable/licensed, no candidates, solve infeasible/timed out); callers
must fall back to the existing greedy _place_blocks reinsertion in that
case, never treat this as the only path.
"""

from __future__ import annotations

import time

from baseline_greedy import _block_bbox, _candidate_positions, _find_earliest_slot, _placement_score
from utils import Bay, Block, check_collisions


def _time_overlaps(a0: float, a1: float, b0: float, b1: float) -> bool:
    return a0 < b1 and b0 < a1


def _candidates_for_block(bi: int, blk_data: dict, bays: list[Bay],
                          bay_placed: list[list[Block]],
                          bay_schedule: list[list[tuple[int, int]]],
                          bay_loads: list[float],
                          w1: float, w2: float, w3: float,
                          bay_weights: list[float],
                          max_per_block: int,
                          deadline: float | None) -> list[tuple]:
    """
    Enumerate up to max_per_block (score, bay_id, x, y, orient_idx, entry,
    exit) candidates for block bi, using the same search
    baseline_greedy._place_blocks already runs for Phase 1/2 -- just keeping
    the top-N by _placement_score instead of only the single best, so the
    MIP below has real alternatives to trade off against other blocks.
    """
    r_time = blk_data["release_time"]
    due = blk_data["due_date"]
    proc = blk_data["processing_time"]
    workload = blk_data["workload"]
    prefs = blk_data["bay_preferences"]
    s_max = max(prefs)

    scored: list[tuple] = []
    for bay_id, bay in enumerate(bays):
        if deadline is not None and time.time() > deadline:
            break
        placed_in_bay = bay_placed[bay_id]
        schedule_in_bay = bay_schedule[bay_id]
        for oi, _ in enumerate(blk_data["shape"]):
            blk_bb = _block_bbox(blk_data, oi)
            candidates = _candidate_positions(bay.width, bay.height, placed_in_bay, blk_bb)
            for cx, cy in candidates:
                if deadline is not None and time.time() > deadline:
                    break
                new_blk = Block(block_id=bi, block_data=blk_data, x=cx, y=cy, orient_idx=oi)
                if not bay.contains_block(new_blk):
                    continue
                entry, exit_t = _find_earliest_slot(
                    new_blk, bay, placed_in_bay, schedule_in_bay,
                    r_time, proc, deadline=deadline,
                )
                if entry is None:
                    continue
                tardiness = max(0.0, exit_t - due)
                score = _placement_score(
                    tardiness, workload, bay_loads, bay_id,
                    s_max - prefs[bay_id], bay_weights, w1, w2, w3,
                    top_y=cy + blk_bb[3],
                )
                scored.append((score, bay_id, cx, cy, oi, entry, exit_t))

    scored.sort(key=lambda t: t[0])
    return scored[:max_per_block]


def reinsert(remove_ids: list[int],
            blocks_data: list[dict],
            bays: list[Bay],
            bay_placed: list[list[Block]],
            bay_schedule: list[list[tuple[int, int]]],
            bay_loads: list[float],
            w1: float, w2: float, w3: float,
            deadline: float | None,
            max_per_block: int = 8,
            solve_time_limit: int = 3) -> dict[int, dict] | None:
    """
    Jointly reinsert remove_ids via a small Xpress MIP.

    Returns {block_id: assignment_dict} on success, or None if Xpress is
    unavailable, any block has zero feasible candidates, the MIP finds no
    feasible/optimal solution, or anything else goes wrong. None is a
    routine, expected outcome (not an error) -- callers must fall back to
    the existing greedy _place_blocks reinsertion whenever this returns None.
    """
    try:
        import xpress as xp
    except Exception:
        return None

    try:
        bay_areas = [bay.width * bay.height for bay in bays]
        avg_area = sum(bay_areas) / len(bays)
        bay_weights = [avg_area / a for a in bay_areas]

        per_block: dict[int, list[tuple]] = {}
        for bi in remove_ids:
            if deadline is not None and time.time() > deadline:
                return None
            cands = _candidates_for_block(
                bi, blocks_data[bi], bays, bay_placed, bay_schedule, bay_loads,
                w1, w2, w3, bay_weights, max_per_block, deadline,
            )
            if not cands:
                return None  # this block has no feasible slot at all right now
            per_block[bi] = cands

        prob = xp.problem()
        y: dict[tuple[int, int], "xp.var"] = {}
        for bi, cands in per_block.items():
            for ci in range(len(cands)):
                y[(bi, ci)] = xp.var(vartype=xp.binary, name=f"y_{bi}_{ci}")
        prob.addVariable(list(y.values()))

        for bi, cands in per_block.items():
            prob.addConstraint(xp.Sum(y[(bi, ci)] for ci in range(len(cands))) == 1)

        ids = list(per_block.keys())
        for a in range(len(ids)):
            if deadline is not None and time.time() > deadline:
                return None
            for b in range(a + 1, len(ids)):
                bi, bj = ids[a], ids[b]
                for ci, (_, bay_i, cx_i, cy_i, oi_i, entry_i, exit_i) in enumerate(per_block[bi]):
                    for cj, (_, bay_j, cx_j, cy_j, oi_j, entry_j, exit_j) in enumerate(per_block[bj]):
                        if bay_i != bay_j or not _time_overlaps(entry_i, exit_i, entry_j, exit_j):
                            continue
                        blk_i = Block(block_id=bi, block_data=blocks_data[bi],
                                     x=cx_i, y=cy_i, orient_idx=oi_i)
                        blk_j = Block(block_id=bj, block_data=blocks_data[bj],
                                     x=cx_j, y=cy_j, orient_idx=oi_j)
                        if check_collisions(bays[bay_i], [blk_i, blk_j]):
                            prob.addConstraint(y[(bi, ci)] + y[(bj, cj)] <= 1)

        objective = xp.Sum(
            per_block[bi][ci][0] * y[(bi, ci)]
            for bi in ids for ci in range(len(per_block[bi]))
        )
        prob.setObjective(objective, sense=xp.minimize)

        remaining = solve_time_limit
        if deadline is not None:
            remaining = max(1, min(solve_time_limit, int(deadline - time.time())))
            if remaining <= 0:
                return None
        prob.controls.maxtime = remaining
        prob.controls.outputlog = 0
        prob.solve()

        if prob.attributes.solstatus not in (xp.SolStatus.OPTIMAL, xp.SolStatus.FEASIBLE):
            return None

        result: dict[int, dict] = {}
        for bi, cands in per_block.items():
            chosen = None
            for ci in range(len(cands)):
                val = prob.getSolution(y[(bi, ci)])
                if val is not None and val > 0.5:
                    chosen = cands[ci]
                    break
            if chosen is None:
                return None
            _, bay_id, cx, cy, oi, entry, exit_t = chosen
            result[bi] = {
                "block_id": bi, "bay_id": bay_id,
                "x": int(round(cx)), "y": int(round(cy)), "orient_idx": oi,
                "entry_time": int(round(entry)), "exit_time": int(round(exit_t)),
            }
        return result
    except Exception:
        return None
