"""
xpress_reinsert.py -- Xpress-assisted exact reinsertion for baseline_greedy's
Phase-3 improvement loop (_improve).

Scope, deliberately narrow: given a small batch of removed blocks (K <= ~5,
see baseline_greedy._improve's k_values) and the fixed context of every
other currently-placed block, choose one (bay, orientation, x, y, entry,
exit) candidate per removed block from a pre-scored candidate list, subject
to no two removed blocks' candidates spatially/temporally conflicting with
each other -- minimizing total candidate cost (_placement_score, the same
scoring function used everywhere else in this codebase).

This is NOT a general geometric packing MIP. Candidates are generated by
the exact same _candidate_positions / _find_earliest_slot search
baseline_greedy already runs for plain greedy placement, so this module
adds no new geometry-modeling risk -- each candidate is already
individually feasible against the fixed (non-removed) context on its own.
The only thing Xpress adds is choosing the JOINTLY best combination among
the K removed blocks instead of placing them one at a time greedily, which
is a small, well-scoped independent-set-style assignment problem: binary
y[block, candidate], "exactly one candidate per block", and a "not both" cut
for every pair of candidates (from two different removed blocks) that
would collide in space and time.

Whatever this proposes is re-validated by utils.check_feasibility in
_improve's caller before being accepted or rolled back, exactly like every
other candidate solution in this codebase -- so an imperfect conflict model
here can only ever cause a proposal to be (correctly) rejected, never
accepted incorrectly. reinsert() returns None on any failure (Xpress not
importable/licensed, no candidates, solve infeasible/timed out); callers
must fall back to the existing greedy _place_blocks reinsertion in that
case, never treat this as the only path.
"""

from __future__ import annotations

import time

from baseline_greedy import _block_bbox, _placement_score
from baseline_greedy import _top_candidates_for_block as _candidates_for_block
from utils import Bay, Block, check_collisions, check_entry, check_exit


def _time_overlaps(a0: float, a1: float, b0: float, b1: float) -> bool:
    return a0 < b1 and b0 < a1


def _current_position_candidate(bi: int, blk_data: dict, current_pos: tuple,
                                bay_loads: list[float], bay_weights: list[float],
                                w1: float, w2: float, w3: float) -> tuple:
    """
    Score a block's CURRENT (bay_id, x, y, orient_idx, entry, exit) as a
    candidate tuple, in the same (score, bay_id, cx, cy, oi, entry, exit_t)
    format _top_candidates_for_block returns -- see reinsert()'s
    guarantee_current_position docstring for why this exists.
    """
    bay_id, cx, cy, oi, entry, exit_t = current_pos
    due = blk_data["due_date"]
    workload = blk_data["workload"]
    prefs = blk_data["bay_preferences"]
    s_max = max(prefs)
    blk_bb = _block_bbox(blk_data, oi)
    tardiness = max(0.0, exit_t - due)
    score = _placement_score(
        tardiness, workload, bay_loads, bay_id,
        s_max - prefs[bay_id], bay_weights, w1, w2, w3,
        top_y=cy + blk_bb[3],
    )
    return (score, bay_id, cx, cy, oi, entry, exit_t)


def _crane_conflict(bay: Bay,
                    blk_i: Block, entry_i: float, exit_i: float,
                    blk_j: Block, entry_j: float, exit_j: float) -> bool:
    """
    True if placing blk_i and blk_j together in the same bay would violate
    the crane operation constraint (Stage 2/3 in utils.check_feasibility) at
    any of the four moments where one could be present during the other's
    crane operation. Presence windows mirror check_feasibility exactly:
    "a_other < t < e_other" (strict both ends).

    2026-07-20 bugfix: the pairwise conflict check in reinsert() below used
    to call check_collisions() only -- steady-state spatial overlap. That
    misses the case where two batch members' bounding footprints never
    overlap in space at the same instant, but one's crane path (entering or
    leaving) is swept-through-obstructed by a layer of the other at the
    moment of that operation, which is a *different, stricter* rule (same-
    or-higher-level layers, not just same-level). A batch that "solved"
    without this check could still be rejected by check_feasibility right
    after -- observed in testing as the identical block pair reappearing in
    violations on the very next repair pass, cascading into forced
    placement of unrelated blocks. See notes/algorithm_overview.md.

    Blocks whose intervals are fully nested (neither is present at the
    other's entry/exit boundary) don't need this check -- any steady-state
    collision between them is already caught by check_collisions().
    """
    if entry_j < entry_i < exit_j and check_entry(bay, [blk_j], blk_i, fast=True):
        return True
    if entry_i < entry_j < exit_i and check_entry(bay, [blk_i], blk_j, fast=True):
        return True
    if entry_j < exit_i < exit_j and check_exit(bay, [blk_j], blk_i, fast=True):
        return True
    if entry_i < exit_j < exit_i and check_exit(bay, [blk_i], blk_j, fast=True):
        return True
    return False


def reinsert(remove_ids: list[int],
            blocks_data: list[dict],
            bays: list[Bay],
            bay_placed: list[list[Block]],
            bay_schedule: list[list[tuple[int, int]]],
            bay_loads: list[float],
            w1: float, w2: float, w3: float,
            deadline: float | None,
            max_per_block: int = 20,
            solve_time_limit: int = 3,
            restrict_bay_id: int | None = None,
            current_positions: dict[int, tuple] | None = None) -> dict[int, dict] | None:
    """
    Jointly reinsert remove_ids via a small Xpress MIP.

    Despite the name, remove_ids need not have ever been placed before --
    candidates are generated purely from the *other* blocks already present
    in bay_placed/bay_schedule/bay_loads (see _top_candidates_for_block),
    so this same function also serves as the joint-batch *insertion*
    primitive for baseline_greedy._place_blocks_batched (Phase 1's
    construction_mode="batched"), not just Phase 2/3 reinsertion.

    Returns {block_id: assignment_dict} on success, or None if Xpress is
    unavailable, any block has zero feasible candidates, the MIP finds no
    feasible/optimal solution, or anything else goes wrong. None is a
    routine, expected outcome (not an error) -- callers must fall back to
    the existing greedy _place_blocks reinsertion whenever this returns None.

    max_per_block was 8 originally; measured fallback rate in that config was
    ~0% success on repair's blocking-chain batches (2026-07-20; see
    notes/algorithm_overview.md). Likely cause: candidates are ranked
    independently per block by _placement_score, with no awareness of the
    OTHER batch member -- and a blocking-chain batch exists specifically
    because the bay is contested there, so both blocks' top few candidates
    tend to cluster in the same desirable spots and collide with each other,
    even when a perfectly good joint arrangement exists further down each
    block's own candidate list. Raised to 20 to give the solver more room to
    find it; still small enough that the O(K^2 x max_per_block^2) pairwise
    conflict-check cost stays cheap for the K<~6 batches seen in practice.

    restrict_bay_id : optional (2026-07-20). Passed straight through to
        _top_candidates_for_block -- when set, candidate generation only
        searches that one bay per block instead of every bay, which is the
        actual fix for bay-scoped joint reinsertion (e.g. "re-optimize this
        whole bay's blocks together") not being able to even finish
        generating candidates for large K (see analysis/bay_mip_probe.py --
        the K=96 probe was searching all 4 bays per block, most of them
        far more crowded than the target one, which was the real cost, not
        the MIP solve). None (default) preserves existing all-bays
        behaviour for every other caller unchanged.
    current_positions : optional (2026-07-20), {block_id: (bay_id, x, y,
        orient_idx, entry, exit_t)}. When a block_id has an entry here, its
        CURRENT position is scored (via _placement_score, same formula as
        every other candidate) and appended to that block's candidate list
        if not already present -- guarantees at least one jointly-feasible
        combination always exists whenever every block's current position is
        provided (e.g. re-optimizing a whole bay's currently-placed blocks
        together: "everyone stays exactly where they are" trivially has zero
        pairwise conflicts, since that's how they were already arranged).
        This does NOT bias the solver toward keeping blocks in place -- it's
        still just one candidate among many, competing on the same score, so
        anything that's actually a real improvement and doesn't conflict
        with other picks is still preferred. It only prevents the solve from
        going INFEASIBLE when a real combination is known to already exist
        but didn't happen to make it into any block's independently-ranked
        top max_per_block (2026-07-20: observed on analysis/bay_mip_probe.py
        -- a 52-block whole-bay reinsertion came back solstatus=3/infeasible
        even at max_per_block=40, because several blocks only had 2-8
        geometrically valid candidates in that bay at all, and evidently
        none of the independently-top-ranked combinations happened to be
        mutually compatible). None (default) -- no guarantee added, existing
        behaviour unchanged for every other caller.
    """
    try:
        import xpress as xp
    except Exception:
        return None

    try:
        bay_areas = [bay.width * bay.height for bay in bays]
        avg_area = sum(bay_areas) / len(bays)
        bay_weights = [avg_area / a for a in bay_areas]

        _t_cand0 = time.time()
        per_block: dict[int, list[tuple]] = {}
        for bi in remove_ids:
            if deadline is not None and time.time() > deadline:
                print(f"[xpress_reinsert] DEBUG bail: deadline hit before candidates for block {bi} "
                      f"(remaining={remove_ids})")
                return None
            cands = _candidates_for_block(
                bi, blocks_data[bi], bays, bay_placed, bay_schedule, bay_loads,
                w1, w2, w3, bay_weights, max_per_block, deadline,
                restrict_bay_id=restrict_bay_id,
            )
            if current_positions is not None and bi in current_positions:
                current_cand = _current_position_candidate(
                    bi, blocks_data[bi], current_positions[bi],
                    bay_loads, bay_weights, w1, w2, w3,
                )
                already_present = any(
                    c[1:] == current_cand[1:] for c in cands
                )
                if not already_present:
                    cands = cands + [current_cand]
            if not cands:
                print(f"[xpress_reinsert] DEBUG bail: block {bi} has 0 candidates "
                      f"(batch={remove_ids})")
                return None  # this block has no feasible slot at all right now
            per_block[bi] = cands
        _t_cand1 = time.time()

        prob = xp.problem()
        y: dict[tuple[int, int], "xp.var"] = {}
        for bi, cands in per_block.items():
            for ci in range(len(cands)):
                y[(bi, ci)] = xp.var(vartype=xp.binary, name=f"y_{bi}_{ci}")
        prob.addVariable(list(y.values()))

        for bi, cands in per_block.items():
            prob.addConstraint(xp.Sum(y[(bi, ci)] for ci in range(len(cands))) == 1)

        ids = list(per_block.keys())
        for a in range(len(ids)):
            if deadline is not None and time.time() > deadline:
                return None
            for b in range(a + 1, len(ids)):
                bi, bj = ids[a], ids[b]
                for ci, (_, bay_i, cx_i, cy_i, oi_i, entry_i, exit_i) in enumerate(per_block[bi]):
                    for cj, (_, bay_j, cx_j, cy_j, oi_j, entry_j, exit_j) in enumerate(per_block[bj]):
                        if bay_i != bay_j or not _time_overlaps(entry_i, exit_i, entry_j, exit_j):
                            continue
                        blk_i = Block(block_id=bi, block_data=blocks_data[bi],
                                     x=cx_i, y=cy_i, orient_idx=oi_i)
                        blk_j = Block(block_id=bj, block_data=blocks_data[bj],
                                     x=cx_j, y=cy_j, orient_idx=oi_j)
                        # Two reasons a (candidate_i, candidate_j) pair can't
                        # coexist: steady-state spatial overlap (same-level
                        # collision) OR a crane operation obstruction (one's
                        # entry/exit swept-blocked by the other's same-or-
                        # higher layers) -- these are different rules and
                        # both need checking, not just the first.
                        if (check_collisions(bays[bay_i], [blk_i, blk_j])
                                or _crane_conflict(bays[bay_i], blk_i, entry_i, exit_i,
                                                   blk_j, entry_j, exit_j)):
                            prob.addConstraint(y[(bi, ci)] + y[(bj, cj)] <= 1)

        _t_pairs1 = time.time()

        objective = xp.Sum(
            per_block[bi][ci][0] * y[(bi, ci)]
            for bi in ids for ci in range(len(per_block[bi]))
        )
        prob.setObjective(objective, sense=xp.minimize)

        remaining = solve_time_limit
        if deadline is not None:
            remaining = max(1, min(solve_time_limit, int(deadline - time.time())))
            if remaining <= 0:
                print(f"[xpress_reinsert] DEBUG bail: no time left before solve (batch={remove_ids})")
                return None
        # prob.controls.maxtime is an integer Xpress control -- int() guards
        # against a caller passing a float solve_time_limit (maxtime would
        # otherwise raise xpress.ModelError deep inside solve(), which
        # looks like a solver failure rather than a caller type mismatch).
        prob.controls.maxtime = int(remaining)
        prob.controls.outputlog = 0
        _t_solve0 = time.time()
        prob.solve()
        _t_solve1 = time.time()

        # 2026-07-21: timing breakdown -- added to find out whether candidate
        # generation (all-bays search per block, no restrict_bay_id for this
        # general call path unlike wholebay's), the O(K^2 x candidates^2)
        # pairwise conflict construction, or the MIP solve itself dominates
        # a given call's cost, before deciding where to optimize next.
        print(f"[xpress_reinsert] TIMING batch_size={len(remove_ids)} "
              f"candidates={_t_cand1-_t_cand0:.3f}s pairs={_t_pairs1-_t_cand1:.3f}s "
              f"solve={_t_solve1-_t_solve0:.3f}s total={_t_solve1-_t_cand0:.3f}s")
        print(f"[xpress_reinsert] DEBUG solstatus={prob.attributes.solstatus} "
              f"batch={remove_ids} n_candidates={[(bi, len(c)) for bi, c in per_block.items()]}")
        if prob.attributes.solstatus not in (xp.SolStatus.OPTIMAL, xp.SolStatus.FEASIBLE):
            return None

        result: dict[int, dict] = {}
        for bi, cands in per_block.items():
            chosen = None
            for ci in range(len(cands)):
                val = prob.getSolution(y[(bi, ci)])
                if val is not None and val > 0.5:
                    chosen = cands[ci]
                    break
            if chosen is None:
                print(f"[xpress_reinsert] DEBUG bail: no chosen candidate extracted for block {bi}")
                return None
            _, bay_id, cx, cy, oi, entry, exit_t = chosen
            result[bi] = {
                "block_id": bi, "bay_id": bay_id,
                "x": int(round(cx)), "y": int(round(cy)), "orient_idx": oi,
                "entry_time": int(round(entry)), "exit_time": int(round(exit_t)),
            }
        return result
    except Exception as _dbg_exc:
        import traceback
        print(f"[xpress_reinsert] DEBUG raised: {_dbg_exc!r}")
        traceback.print_exc()
        return None
