"""
xpress_reinsert.py -- Xpress-assisted exact reinsertion for baseline_greedy's
Phase-3 improvement loop (_improve).

Scope, deliberately narrow: given a small batch of removed blocks (K <= ~5,
see baseline_greedy._improve's k_values) and the fixed context of every
other currently-placed block, choose one (bay, orientation, x, y, entry,
exit) candidate per removed block from a pre-scored candidate list, subject
to no two removed blocks' candidates spatially/temporally conflicting with
each other -- minimizing total candidate cost (_placement_score, the same
scoring function used everywhere else in this codebase).

This is NOT a general geometric packing MIP. Candidates are generated by
the exact same _candidate_positions / _find_earliest_slot search
baseline_greedy already runs for plain greedy placement, so this module
adds no new geometry-modeling risk -- each candidate is already
individually feasible against the fixed (non-removed) context on its own.
The only thing Xpress adds is choosing the JOINTLY best combination among
the K removed blocks instead of placing them one at a time greedily, which
is a small, well-scoped independent-set-style assignment problem: binary
y[block, candidate], "exactly one candidate per block", and a "not both" cut
for every pair of candidates (from two different removed blocks) that
would collide in space and time.

Whatever this proposes is re-validated by utils.check_feasibility in
_improve's caller before being accepted or rolled back, exactly like every
other candidate solution in this codebase -- so an imperfect conflict model
here can only ever cause a proposal to be (correctly) rejected, never
accepted incorrectly. reinsert() returns None on any failure (Xpress not
importable/licensed, no candidates, solve infeasible/timed out); callers
must fall back to the existing greedy _place_blocks reinsertion in that
case, never treat this as the only path.
"""

from __future__ import annotations

import time

from baseline_greedy import _block_bbox, _placement_score
from baseline_greedy import _top_candidates_for_block as _candidates_for_block
from utils import Bay, Block, _bb_overlap, check_collisions, check_entry, check_exit

# 2026-07-22: batches at or below this size get each other's current
# position cross-injected into their candidate pools (see
# _cross_position_candidate) -- see reinsert()'s call site for why this is
# capped (O(K^2) extra cost, not needed for wholebay's much larger K).
CROSS_INJECT_MAX_K = 5
# 2026-07-22 (user-proposed): skip cross-injecting bi into bj's spot when
# bi's own AABB is more than this much larger than bj's in either axis --
# a cheap, deliberately generous pre-filter (not a correctness gate; the
# real polygon check still happens downstream) to avoid paying for a
# candidate/MIP-variable that's almost certainly going to be geometrically
# hopeless anyway (e.g. injecting a large block into a much smaller one's
# footprint). Generous on purpose: false negatives here only cost a missed
# optimization opportunity, never correctness, so err toward not filtering
# out genuinely-plausible swaps.
CROSS_INJECT_SIZE_SLACK = 1.3

# 2026-07-22 (experiment/same-bay-first branch): toggle for A/B-testing
# whether the same-bay-first fast path (see reinsert()'s call site) is
# trapping blocks in a congested bay by never even generating an
# other-bay candidate once the current bay alone fills max_per_block --
# see notes/ogc2026_p4p6_investigation memory, hypothesis #1. False reverts
# to the original unconditional all-bays scan.
#
# Investigated 2026-07-22: naive block-DUPLICATE stress instances (x4/x8,
# same 250 blocks repeated) gave inconsistent, direction-flipping results
# (OFF ~1% better at x4, ON ~1.7% better at x8) -- these turned out to be a
# poor proxy, since duplicating identical blocks creates an artificial
# preference-clustering that a real large/heterogeneous instance wouldn't
# have to the same degree. A more realistic test (1000 blocks pooled from 5
# DIFFERENT local instances, each keeping its own shape/preferences) showed
# ON consistently better across 4 repeated runs (4-15% margin, direction
# never flipped) -- same-bay-first does NOT look like the P4-6 stagnation's
# culprit after all, and may genuinely help on realistic heterogeneous
# instances. Kept enabled (True) as the default; this toggle is left in
# place as a debug/re-verification knob, not because the investigation is
# still open.
SAME_BAY_FIRST_ENABLED = True


def _time_overlaps(a0: float, a1: float, b0: float, b1: float) -> bool:
    return a0 < b1 and b0 < a1


def _current_position_candidate(bi: int, blk_data: dict, current_pos: tuple,
                                bay_loads: list[float], bay_weights: list[float],
                                w1: float, w2: float, w3: float) -> tuple:
    """
    Score a block's CURRENT (bay_id, x, y, orient_idx, entry, exit) as a
    candidate tuple, in the same (score, bay_id, cx, cy, oi, entry, exit_t)
    format _top_candidates_for_block returns -- see reinsert()'s
    guarantee_current_position docstring for why this exists.
    """
    bay_id, cx, cy, oi, entry, exit_t = current_pos
    due = blk_data["due_date"]
    workload = blk_data["workload"]
    prefs = blk_data["bay_preferences"]
    s_max = max(prefs)
    blk_bb = _block_bbox(blk_data, oi)
    tardiness = max(0.0, exit_t - due)
    score = _placement_score(
        tardiness, workload, bay_loads, bay_id,
        s_max - prefs[bay_id], bay_weights, w1, w2, w3,
        top_y=cy + blk_bb[3],
    )
    return (score, bay_id, cx, cy, oi, entry, exit_t)


def _cross_position_candidate(bi: int, blk_data: dict, my_orient_idx: int,
                              other_pos: tuple, bay_loads: list[float],
                              bay_weights: list[float],
                              w1: float, w2: float, w3: float) -> tuple:
    """
    2026-07-22 (user-proposed). Score block bi occupying a DIFFERENT block's
    current (bay_id, x, y) -- bi's own orientation/shape/processing_time,
    the other block's position and entry time as a starting guess -- as a
    candidate tuple, same format as _current_position_candidate.

    Motivation: on a congested instance, Z1 tardiness caused by two blocks
    mutually blocking each other's spot ("deadlock") can only be resolved by
    literally swapping their positions -- but each block's own candidate
    list is independently ranked and capped (max_per_block, usually 20), so
    the OTHER block's exact spot may simply never be ranked highly enough to
    survive the cap on its own merits, even though "swap" specifically
    selects these two blocks BECAUSE they're blocking each other. Without
    that spot in the pool, the joint MIP structurally cannot express the
    swap at all, no matter how obviously good it would be. Injecting it
    explicitly guarantees the solver always gets to at least CONSIDER the
    literal swap, whether or not the AABB-lower-bound ranking would have
    surfaced it.

    Deliberately cheap (no _find_earliest_slot search) -- like every other
    candidate in this codebase, this is just a suggestion; the pairwise
    conflict check still screens it against the rest of this batch, and the
    caller re-validates the whole trial with the real check_feasibility
    before ever accepting it. Uses bi's OWN orientation (not the other
    block's) since a different block's shape at that orientation index may
    not even correspond to a compatible orientation for bi -- and the other
    block's entry time as a starting guess (the natural "swap" hypothesis:
    each block takes over where the other one was, when it was there),
    combined with bi's own processing_time for the exit.
    """
    other_bay_id, other_cx, other_cy, _other_oi, other_entry, _other_exit = other_pos
    r_time = blk_data["release_time"]
    due = blk_data["due_date"]
    proc = blk_data["processing_time"]
    workload = blk_data["workload"]
    prefs = blk_data["bay_preferences"]
    s_max = max(prefs)
    blk_bb = _block_bbox(blk_data, my_orient_idx)

    entry = max(r_time, other_entry)
    exit_t = entry + proc
    tardiness = max(0.0, exit_t - due)
    score = _placement_score(
        tardiness, workload, bay_loads, other_bay_id,
        s_max - prefs[other_bay_id], bay_weights, w1, w2, w3,
        top_y=other_cy + blk_bb[3],
    )
    return (score, other_bay_id, other_cx, other_cy, my_orient_idx, entry, exit_t)


def _crane_conflict(bay: Bay,
                    blk_i: Block, entry_i: float, exit_i: float,
                    blk_j: Block, entry_j: float, exit_j: float) -> bool:
    """
    True if placing blk_i and blk_j together in the same bay would violate
    the crane operation constraint (Stage 2/3 in utils.check_feasibility) at
    any of the four moments where one could be present during the other's
    crane operation. Presence windows mirror check_feasibility exactly:
    "a_other < t < e_other" (strict both ends).

    2026-07-20 bugfix: the pairwise conflict check in reinsert() below used
    to call check_collisions() only -- steady-state spatial overlap. That
    misses the case where two batch members' bounding footprints never
    overlap in space at the same instant, but one's crane path (entering or
    leaving) is swept-through-obstructed by a layer of the other at the
    moment of that operation, which is a *different, stricter* rule (same-
    or-higher-level layers, not just same-level). A batch that "solved"
    without this check could still be rejected by check_feasibility right
    after -- observed in testing as the identical block pair reappearing in
    violations on the very next repair pass, cascading into forced
    placement of unrelated blocks. See notes/algorithm_overview.md.

    Blocks whose intervals are fully nested (neither is present at the
    other's entry/exit boundary) don't need this check -- any steady-state
    collision between them is already caught by check_collisions().
    """
    if entry_j < entry_i < exit_j and check_entry(bay, [blk_j], blk_i, fast=True):
        return True
    if entry_i < entry_j < exit_i and check_entry(bay, [blk_i], blk_j, fast=True):
        return True
    if entry_j < exit_i < exit_j and check_exit(bay, [blk_j], blk_i, fast=True):
        return True
    if entry_i < exit_j < exit_i and check_exit(bay, [blk_i], blk_j, fast=True):
        return True
    return False


def reinsert(remove_ids: list[int],
            blocks_data: list[dict],
            bays: list[Bay],
            bay_placed: list[list[Block]],
            bay_schedule: list[list[tuple[int, int]]],
            bay_loads: list[float],
            w1: float, w2: float, w3: float,
            deadline: float | None,
            max_per_block: int = 20,
            solve_time_limit: int = 3,
            restrict_bay_id: int | None = None,
            current_positions: dict[int, tuple] | None = None) -> dict[int, dict] | None:
    """
    Jointly reinsert remove_ids via a small Xpress MIP.

    Despite the name, remove_ids need not have ever been placed before --
    candidates are generated purely from the *other* blocks already present
    in bay_placed/bay_schedule/bay_loads (see _top_candidates_for_block),
    so this same function also serves as the joint-batch *insertion*
    primitive for baseline_greedy._place_blocks_batched (Phase 1's
    construction_mode="batched"), not just Phase 2/3 reinsertion.

    Returns {block_id: assignment_dict} on success, or None if Xpress is
    unavailable, any block has zero feasible candidates, the MIP finds no
    feasible/optimal solution, or anything else goes wrong. None is a
    routine, expected outcome (not an error) -- callers must fall back to
    the existing greedy _place_blocks reinsertion whenever this returns None.

    max_per_block was 8 originally; measured fallback rate in that config was
    ~0% success on repair's blocking-chain batches (2026-07-20; see
    notes/algorithm_overview.md). Likely cause: candidates are ranked
    independently per block by _placement_score, with no awareness of the
    OTHER batch member -- and a blocking-chain batch exists specifically
    because the bay is contested there, so both blocks' top few candidates
    tend to cluster in the same desirable spots and collide with each other,
    even when a perfectly good joint arrangement exists further down each
    block's own candidate list. Raised to 20 to give the solver more room to
    find it; still small enough that the O(K^2 x max_per_block^2) pairwise
    conflict-check cost stays cheap for the K<~6 batches seen in practice.

    restrict_bay_id : optional (2026-07-20). Passed straight through to
        _top_candidates_for_block -- when set, candidate generation only
        searches that one bay per block instead of every bay, which is the
        actual fix for bay-scoped joint reinsertion (e.g. "re-optimize this
        whole bay's blocks together") not being able to even finish
        generating candidates for large K (see analysis/bay_mip_probe.py --
        the K=96 probe was searching all 4 bays per block, most of them
        far more crowded than the target one, which was the real cost, not
        the MIP solve). None (default) preserves existing all-bays
        behaviour for every other caller unchanged.
    current_positions : optional (2026-07-20), {block_id: (bay_id, x, y,
        orient_idx, entry, exit_t)}. When a block_id has an entry here, its
        CURRENT position is scored (via _placement_score, same formula as
        every other candidate) and appended to that block's candidate list
        if not already present -- guarantees at least one jointly-feasible
        combination always exists whenever every block's current position is
        provided (e.g. re-optimizing a whole bay's currently-placed blocks
        together: "everyone stays exactly where they are" trivially has zero
        pairwise conflicts, since that's how they were already arranged).
        This does NOT bias the solver toward keeping blocks in place -- it's
        still just one candidate among many, competing on the same score, so
        anything that's actually a real improvement and doesn't conflict
        with other picks is still preferred. It only prevents the solve from
        going INFEASIBLE when a real combination is known to already exist
        but didn't happen to make it into any block's independently-ranked
        top max_per_block (2026-07-20: observed on analysis/bay_mip_probe.py
        -- a 52-block whole-bay reinsertion came back solstatus=3/infeasible
        even at max_per_block=40, because several blocks only had 2-8
        geometrically valid candidates in that bay at all, and evidently
        none of the independently-top-ranked combinations happened to be
        mutually compatible). None (default) -- no guarantee added, existing
        behaviour unchanged for every other caller.
    """
    try:
        import xpress as xp
    except Exception:
        return None

    try:
        bay_areas = [bay.width * bay.height for bay in bays]
        avg_area = sum(bay_areas) / len(bays)
        bay_weights = [avg_area / a for a in bay_areas]

        _t_cand0 = time.time()
        per_block: dict[int, list[tuple]] = {}
        for bi in remove_ids:
            if deadline is not None and time.time() > deadline:
                print(f"[xpress_reinsert] DEBUG bail: deadline hit before candidates for block {bi} "
                      f"(remaining={remove_ids})")
                return None
            # 2026-07-22: same-bay-first fast path. The general (non-wholebay)
            # call path here always searched every bay x orientation for
            # every block, even though most repair batches exist because the
            # block's OWN current bay is contested (see this function's
            # docstring on why max_per_block was raised) -- on a congested
            # bay this full all-bays scan measured as the dominant cost of a
            # repair round (6+ seconds for a 2-3 block batch, see
            # notes/algorithm_overview.md). If the block's current bay alone
            # already yields a full max_per_block quota of candidates (via
            # the same AABB-lower-bound ranking used everywhere else), that
            # bay is not sparse -- scanning the other bays too is very
            # unlikely to change the outcome, so skip it. If the current bay
            # comes up short (sparse/contested-out), fall through to the
            # unrestricted full search exactly as before -- this never
            # narrows the search in the case that actually needs it (a block
            # whose current bay genuinely has no good options left), only in
            # the case where its current bay already has plenty.
            cands = None
            if SAME_BAY_FIRST_ENABLED and restrict_bay_id is None and current_positions is not None and bi in current_positions:
                own_bay = current_positions[bi][0]
                same_bay_cands = _candidates_for_block(
                    bi, blocks_data[bi], bays, bay_placed, bay_schedule, bay_loads,
                    w1, w2, w3, bay_weights, max_per_block, deadline,
                    restrict_bay_id=own_bay,
                )
                if len(same_bay_cands) >= max_per_block:
                    cands = same_bay_cands
            if cands is None:
                cands = _candidates_for_block(
                    bi, blocks_data[bi], bays, bay_placed, bay_schedule, bay_loads,
                    w1, w2, w3, bay_weights, max_per_block, deadline,
                    restrict_bay_id=restrict_bay_id,
                )
            if current_positions is not None and bi in current_positions:
                current_cand = _current_position_candidate(
                    bi, blocks_data[bi], current_positions[bi],
                    bay_loads, bay_weights, w1, w2, w3,
                )
                already_present = any(
                    c[1:] == current_cand[1:] for c in cands
                )
                if not already_present:
                    cands = cands + [current_cand]
            # 2026-07-22 (user-proposed): also inject each OTHER batch
            # member's current position as a candidate for bi -- see
            # _cross_position_candidate's docstring. Gated to small batches
            # (CROSS_INJECT_MAX_K) since this is O(K) extra candidates per
            # block, O(K^2) for the whole batch -- fine for "swap" (always
            # exactly K=2) and other small-k operators, but would add
            # needless cost to wholebay's much larger batches (K up to
            # ~170), which already has its own current_positions-based
            # fallback guarantee (_current_position_candidate above) and
            # doesn't need this cross-injection to make progress.
            if (current_positions is not None and bi in current_positions
                    and len(remove_ids) <= CROSS_INJECT_MAX_K):
                my_orient_idx = current_positions[bi][3]
                my_bb = _block_bbox(blocks_data[bi], my_orient_idx)
                my_w, my_h = my_bb[2] - my_bb[0], my_bb[3] - my_bb[1]
                for bj in remove_ids:
                    if bj == bi or bj not in current_positions:
                        continue
                    # cheap AABB size pre-filter (user-proposed) -- skip
                    # injecting bi into bj's spot when bi's own footprint is
                    # clearly too big to plausibly fit there, before paying
                    # for the candidate/MIP-variable at all.
                    other_orient_idx = current_positions[bj][3]
                    other_bb = _block_bbox(blocks_data[bj], other_orient_idx)
                    other_w = other_bb[2] - other_bb[0]
                    other_h = other_bb[3] - other_bb[1]
                    if (my_w > other_w * CROSS_INJECT_SIZE_SLACK
                            or my_h > other_h * CROSS_INJECT_SIZE_SLACK):
                        continue
                    cross_cand = _cross_position_candidate(
                        bi, blocks_data[bi], my_orient_idx, current_positions[bj],
                        bay_loads, bay_weights, w1, w2, w3,
                    )
                    already_present = any(
                        c[1:] == cross_cand[1:] for c in cands
                    )
                    if not already_present:
                        cands = cands + [cross_cand]
            if not cands:
                print(f"[xpress_reinsert] DEBUG bail: block {bi} has 0 candidates "
                      f"(batch={remove_ids})")
                return None  # this block has no feasible slot at all right now
            per_block[bi] = cands
        _t_cand1 = time.time()

        prob = xp.problem()
        y: dict[tuple[int, int], "xp.var"] = {}
        for bi, cands in per_block.items():
            for ci in range(len(cands)):
                y[(bi, ci)] = xp.var(vartype=xp.binary, name=f"y_{bi}_{ci}")
        prob.addVariable(list(y.values()))

        for bi, cands in per_block.items():
            prob.addConstraint(xp.Sum(y[(bi, ci)] for ci in range(len(cands))) == 1)

        # 2026-07-23 (user-proposed): world-space AABB per candidate,
        # precomputed once here rather than inside the O(K^2 x candidates^2)
        # pair loop below. check_collisions/check_entry/check_exit each
        # already have their OWN internal AABB pre-filter (see their
        # docstrings), so this doesn't unlock any new Shapely-skipping those
        # don't already do -- what it skips is everything OUTSIDE that: two
        # full Block() constructions (shape/layer resolution) plus up to
        # three function-call layers (_crane_conflict's own four check_entry/
        # check_exit calls) for every candidate pair whose footprints can
        # never possibly conflict regardless of timing. Candidates spread
        # across a large bay routinely have many same-bay, time-overlapping
        # pairs that are nowhere near each other spatially -- exactly the gap
        # this closes. bb[bi][ci] = (x0, y0, x1, y1) in world coordinates.
        bb: dict[int, list[tuple[float, float, float, float]]] = {}
        for bi, cands in per_block.items():
            blk_bbs = []
            for (_, _, cx, cy, oi, _, _) in cands:
                lx0, ly0, lx1, ly1 = _block_bbox(blocks_data[bi], oi)
                blk_bbs.append((cx + lx0, cy + ly0, cx + lx1, cy + ly1))
            bb[bi] = blk_bbs

        ids = list(per_block.keys())
        for a in range(len(ids)):
            if deadline is not None and time.time() > deadline:
                return None
            for b in range(a + 1, len(ids)):
                bi, bj = ids[a], ids[b]
                for ci, (_, bay_i, cx_i, cy_i, oi_i, entry_i, exit_i) in enumerate(per_block[bi]):
                    for cj, (_, bay_j, cx_j, cy_j, oi_j, entry_j, exit_j) in enumerate(per_block[bj]):
                        if (bay_i != bay_j or not _time_overlaps(entry_i, exit_i, entry_j, exit_j)
                                or not _bb_overlap(bb[bi][ci], bb[bj][cj])):
                            continue
                        blk_i = Block(block_id=bi, block_data=blocks_data[bi],
                                     x=cx_i, y=cy_i, orient_idx=oi_i)
                        blk_j = Block(block_id=bj, block_data=blocks_data[bj],
                                     x=cx_j, y=cy_j, orient_idx=oi_j)
                        # Two reasons a (candidate_i, candidate_j) pair can't
                        # coexist: steady-state spatial overlap (same-level
                        # collision) OR a crane operation obstruction (one's
                        # entry/exit swept-blocked by the other's same-or-
                        # higher layers) -- these are different rules and
                        # both need checking, not just the first.
                        if (check_collisions(bays[bay_i], [blk_i, blk_j])
                                or _crane_conflict(bays[bay_i], blk_i, entry_i, exit_i,
                                                   blk_j, entry_j, exit_j)):
                            prob.addConstraint(y[(bi, ci)] + y[(bj, cj)] <= 1)

        _t_pairs1 = time.time()

        objective = xp.Sum(
            per_block[bi][ci][0] * y[(bi, ci)]
            for bi in ids for ci in range(len(per_block[bi]))
        )
        prob.setObjective(objective, sense=xp.minimize)

        remaining = solve_time_limit
        if deadline is not None:
            remaining = max(1, min(solve_time_limit, int(deadline - time.time())))
            if remaining <= 0:
                print(f"[xpress_reinsert] DEBUG bail: no time left before solve (batch={remove_ids})")
                return None
        # prob.controls.maxtime is an integer Xpress control -- int() guards
        # against a caller passing a float solve_time_limit (maxtime would
        # otherwise raise xpress.ModelError deep inside solve(), which
        # looks like a solver failure rather than a caller type mismatch).
        prob.controls.maxtime = int(remaining)
        prob.controls.outputlog = 0
        _t_solve0 = time.time()
        prob.solve()
        _t_solve1 = time.time()

        # 2026-07-21: timing breakdown -- added to find out whether candidate
        # generation (all-bays search per block, no restrict_bay_id for this
        # general call path unlike wholebay's), the O(K^2 x candidates^2)
        # pairwise conflict construction, or the MIP solve itself dominates
        # a given call's cost, before deciding where to optimize next.
        print(f"[xpress_reinsert] TIMING batch_size={len(remove_ids)} "
              f"candidates={_t_cand1-_t_cand0:.3f}s pairs={_t_pairs1-_t_cand1:.3f}s "
              f"solve={_t_solve1-_t_solve0:.3f}s total={_t_solve1-_t_cand0:.3f}s")
        print(f"[xpress_reinsert] DEBUG solstatus={prob.attributes.solstatus} "
              f"batch={remove_ids} n_candidates={[(bi, len(c)) for bi, c in per_block.items()]}")
        if prob.attributes.solstatus not in (xp.SolStatus.OPTIMAL, xp.SolStatus.FEASIBLE):
            return None

        result: dict[int, dict] = {}
        for bi, cands in per_block.items():
            chosen = None
            for ci in range(len(cands)):
                val = prob.getSolution(y[(bi, ci)])
                if val is not None and val > 0.5:
                    chosen = cands[ci]
                    break
            if chosen is None:
                print(f"[xpress_reinsert] DEBUG bail: no chosen candidate extracted for block {bi}")
                return None
            _, bay_id, cx, cy, oi, entry, exit_t = chosen
            result[bi] = {
                "block_id": bi, "bay_id": bay_id,
                "x": int(round(cx)), "y": int(round(cy)), "orient_idx": oi,
                "entry_time": int(round(entry)), "exit_time": int(round(exit_t)),
            }
        return result
    except Exception as _dbg_exc:
        import traceback
        print(f"[xpress_reinsert] DEBUG raised: {_dbg_exc!r}")
        traceback.print_exc()
        return None
